/**
 * Cache lifetimes, tied to the filing calendar. Every resource has an explicit
 * TTL and a stated reason; `TTL-POLICY.md` beside this file is the prose
 * version, and `ttl-policy.test.ts` fails if any resource kind ever loses its
 * reason string. The reason travels with the cached entry, so a stale-looking
 * value can always explain why it was trusted.
 *
 * The governing distinction: accessioned bytes are immutable, indexes are not.
 */
import { classifyUrl } from '../sec/endpoints.ts';
import type { EdgarResourceKind } from '../sec/errors.ts';
import {
  DAY_MS,
  easternDate,
  isAcceptanceOpen,
  isBusinessDay,
  msUntilNextAcceptanceOpen,
} from './filing-calendar.ts';

const MINUTE_MS = 60_000;
const HOUR_MS = 60 * MINUTE_MS;

/** How long a 404 is remembered. */
export const NEGATIVE_TTL_MS = HOUR_MS;

/**
 * How long after acceptance an accession's directory listing is still treated
 * as mutable. EDGAR generates the rendered R-files, `MetaLinks.json` and
 * `Financial_Report.xlsx` after the filing is accepted, so a listing fetched
 * minutes after a filing is genuinely incomplete rather than authoritative.
 */
export const ARCHIVE_SETTLING_MS = DAY_MS;

export type TtlDecision =
  | { readonly immutable: true; readonly resource: EdgarResourceKind; readonly reason: string }
  | {
      readonly immutable: false;
      readonly resource: EdgarResourceKind;
      readonly ttlMs: number;
      readonly reason: string;
    };

export interface TtlContext {
  readonly now: number;
  /** Acceptance instant of the filing an archive URL belongs to, when known. */
  readonly filedAtEpochMs?: number | null;
  /** `true` when caching an absence rather than a payload. */
  readonly negative?: boolean;
}

/**
 * One sentence per resource, stated once. Anything not in this table is not
 * cached, because an unexplained lifetime is the thing this table exists to
 * prevent.
 */
export const TTL_REASONS: Readonly<Record<EdgarResourceKind, string>> = {
  'ticker-map':
    'Regenerated by the SEC roughly daily; a ticker-to-CIK mapping changes rarely and a stale miss self-corrects on the next lookup. 7 days.',
  submissions:
    'An index, not a document: it changes the moment the filer files. Lifetime follows EDGAR acceptance hours - 1h while filings can arrive, 6h once the window closes on a business day, 24h on weekends and holidays when nothing can be accepted.',
  'submissions-overflow':
    'Older slices of the same index. They change only when the recent block overflows, which is a multi-month event for any filer. 7 days.',
  'company-facts': 'Derived from disseminated XBRL, so it changes only when the filer files. 24h.',
  'company-concept': 'Same underlying data as company facts, narrower slice. 24h.',
  'filing-index':
    'The directory listing grows for about a day after acceptance while EDGAR generates the rendered R-files and MetaLinks. Mutable for that settling period, immutable afterwards.',
  'archive-document':
    'Immutable. Accessioned bytes never change - a correction is a new accession, not an edit to an old one.',
  'daily-index':
    'A closed day is final and cached forever. The current day is still filling, so 15 minutes during acceptance hours and until the next open outside them.',
};

/** The lifetime for a URL, with the reason that justifies it. */
export function ttlFor(url: string, context: TtlContext): TtlDecision {
  const resource = classifyUrl(url);

  if (resource === null) {
    throw new Error(
      `Refusing to cache an unclassified EDGAR URL: ${url}. Every cached resource needs a TTL and a stated reason.`,
    );
  }

  const reason = TTL_REASONS[resource];

  if (context.negative === true) {
    return {
      immutable: false,
      resource,
      ttlMs: NEGATIVE_TTL_MS,
      reason: `Absence cached for 1h: a missing period or a missing exhibit is a real state worth remembering, but short enough to notice a late filing. (${reason})`,
    };
  }

  switch (resource) {
    case 'archive-document':
      return { immutable: true, resource, reason };

    case 'filing-index': {
      const filedAt = context.filedAtEpochMs ?? null;
      const settled = filedAt !== null && context.now - filedAt > ARCHIVE_SETTLING_MS;

      return settled
        ? { immutable: true, resource, reason }
        : { immutable: false, resource, ttlMs: HOUR_MS, reason };
    }

    case 'daily-index': {
      const indexedDay = dailyIndexDate(url);

      if (indexedDay !== null && indexedDay < easternDate(context.now)) {
        return { immutable: true, resource, reason };
      }

      return {
        immutable: false,
        resource,
        ttlMs: isAcceptanceOpen(context.now)
          ? 15 * MINUTE_MS
          : Math.max(MINUTE_MS, msUntilNextAcceptanceOpen(context.now)),
        reason,
      };
    }

    case 'submissions':
      return { immutable: false, resource, ttlMs: submissionsTtlMs(context.now), reason };

    case 'submissions-overflow':
      return { immutable: false, resource, ttlMs: 7 * DAY_MS, reason };

    case 'company-facts':
    case 'company-concept':
      return { immutable: false, resource, ttlMs: DAY_MS, reason };

    case 'ticker-map':
      return { immutable: false, resource, ttlMs: 7 * DAY_MS, reason };
  }
}

function submissionsTtlMs(now: number): number {
  if (isAcceptanceOpen(now)) {
    return HOUR_MS;
  }

  return isBusinessDay(now) ? 6 * HOUR_MS : DAY_MS;
}

function dailyIndexDate(url: string): string | null {
  const match = /\/(?:form|company|master)\.(\d{4})(\d{2})(\d{2})\.idx$/.exec(url);

  return match === null ? null : `${match[1]}-${match[2]}-${match[3]}`;
}

/** Absolute expiry for an entry, or `null` when the resource is immutable. */
export function expiresAtFor(decision: TtlDecision, now: number): number | null {
  return decision.immutable ? null : now + decision.ttlMs;
}
